name: Docker images

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Build images
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v1
        
        - name: Login to DockerHub
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        
        - name: Get the latest tag
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

        - name: Build image from alpine - v5
          run: make build-alpine-v5 TAG="${{steps.vars.outputs.tag}}"

        - name: Push alpine-based image - v5
          run: make push-alpine-v5 TAG="${{steps.vars.outputs.tag}}"

        - name: Build image from alpine - v4
          run: make build-alpine TAG="${{steps.vars.outputs.tag}}"

        - name: Push alpine-based image - v4
          run: make push-alpine TAG="${{steps.vars.outputs.tag}}"

        - name: Logout from DockerHub
          run: docker logout